on: [push]

defaults:
  run:
    working-directory: myapp

jobs:
  build:
    working-directory: myapp
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: build with Maven
        run: mvn compile

      - name: test with Maven
        run: mvn verify


