on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: check repo
        run: pwd
      - name: check folders
        run: ls
      - name: build with Maven
        run: mvn compile --file myapp/pom.xml

      - name: test with Maven
        run: mvn verify


